version: 2
archives:
- id: archive
  name_template: '{{ .Binary }}-{{ .Tag }}-{{ .Os }}-{{ .Arch }}'
builds:
- binary: pulumi-resource-kubeconfig
  env:
  - CGO_ENABLED=0
  - GO111MODULE=on
  goarch:
  - amd64
  - arm64
  goos:
  - darwin
  - windows
  - linux
  ldflags:
  - -s
  - -w
  - -X main.Version={{.Tag}}
  main: .
changelog:
  disable: true
release:
  prerelease: auto
snapshot:
  name_template: '{{ .Tag }}-SNAPSHOT'