// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace PiersKarsenbarg.Kubeconfig
{
    [KubeconfigResourceType("kubeconfig:index:AksKubeConfig")]
    public partial class AksKubeConfig : global::Pulumi.ComponentResource
    {
        /// <summary>
        /// Kubeconfig returned from AKS cluster
        /// </summary>
        [Output("kubeconfig")]
        public Output<string> Kubeconfig { get; private set; } = null!;


        /// <summary>
        /// Create a AksKubeConfig resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public AksKubeConfig(string name, AksKubeConfigArgs args, ComponentResourceOptions? options = null)
            : base("kubeconfig:index:AksKubeConfig", name, args ?? new AksKubeConfigArgs(), MakeResourceOptions(options, ""), remote: true)
        {
        }

        private static ComponentResourceOptions MakeResourceOptions(ComponentResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new ComponentResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/pierskarsenbarg/pulumi-kubeconfig",
            };
            var merged = ComponentResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
    }

    public sealed class AksKubeConfigArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Name of the AKS cluster you want the Kubeconfig from.
        /// </summary>
        [Input("clusterName", required: true)]
        public Input<string> ClusterName { get; set; } = null!;

        /// <summary>
        /// Specify whether you want to retrieve the admin kubeconfig or the user kubeconfig. Default value is false
        /// </summary>
        [Input("isAdmin")]
        public Input<bool>? IsAdmin { get; set; }

        /// <summary>
        /// Name of the resource group that the cluster is part of.
        /// </summary>
        [Input("resourceGroupName", required: true)]
        public Input<string> ResourceGroupName { get; set; } = null!;

        public AksKubeConfigArgs()
        {
        }
        public static new AksKubeConfigArgs Empty => new AksKubeConfigArgs();
    }
}
