// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package kubeconfig

import (
	"context"
	"reflect"

	"errors"
	"github.com/pierskarsenbarg/pulumi-kubeconfig/sdk/go/kubeconfig/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type AksKubeConfig struct {
	pulumi.ResourceState

	// Kubeconfig returned from AKS cluster
	Kubeconfig pulumi.StringOutput `pulumi:"kubeconfig"`
}

// NewAksKubeConfig registers a new resource with the given unique name, arguments, and options.
func NewAksKubeConfig(ctx *pulumi.Context,
	name string, args *AksKubeConfigArgs, opts ...pulumi.ResourceOption) (*AksKubeConfig, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.ClusterName == nil {
		return nil, errors.New("invalid value for required argument 'ClusterName'")
	}
	if args.ResourceGroupName == nil {
		return nil, errors.New("invalid value for required argument 'ResourceGroupName'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource AksKubeConfig
	err := ctx.RegisterRemoteComponentResource("kubeconfig:index:AksKubeConfig", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

type aksKubeConfigArgs struct {
	// Name of the AKS cluster you want the Kubeconfig from.
	ClusterName string `pulumi:"clusterName"`
	// Specify whether you want to retrieve the admin kubeconfig or the user kubeconfig. Default value is false
	IsAdmin *bool `pulumi:"isAdmin"`
	// Name of the resource group that the cluster is part of.
	ResourceGroupName string `pulumi:"resourceGroupName"`
}

// The set of arguments for constructing a AksKubeConfig resource.
type AksKubeConfigArgs struct {
	// Name of the AKS cluster you want the Kubeconfig from.
	ClusterName pulumi.StringInput
	// Specify whether you want to retrieve the admin kubeconfig or the user kubeconfig. Default value is false
	IsAdmin pulumi.BoolPtrInput
	// Name of the resource group that the cluster is part of.
	ResourceGroupName pulumi.StringInput
}

func (AksKubeConfigArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*aksKubeConfigArgs)(nil)).Elem()
}

type AksKubeConfigInput interface {
	pulumi.Input

	ToAksKubeConfigOutput() AksKubeConfigOutput
	ToAksKubeConfigOutputWithContext(ctx context.Context) AksKubeConfigOutput
}

func (*AksKubeConfig) ElementType() reflect.Type {
	return reflect.TypeOf((**AksKubeConfig)(nil)).Elem()
}

func (i *AksKubeConfig) ToAksKubeConfigOutput() AksKubeConfigOutput {
	return i.ToAksKubeConfigOutputWithContext(context.Background())
}

func (i *AksKubeConfig) ToAksKubeConfigOutputWithContext(ctx context.Context) AksKubeConfigOutput {
	return pulumi.ToOutputWithContext(ctx, i).(AksKubeConfigOutput)
}

type AksKubeConfigOutput struct{ *pulumi.OutputState }

func (AksKubeConfigOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**AksKubeConfig)(nil)).Elem()
}

func (o AksKubeConfigOutput) ToAksKubeConfigOutput() AksKubeConfigOutput {
	return o
}

func (o AksKubeConfigOutput) ToAksKubeConfigOutputWithContext(ctx context.Context) AksKubeConfigOutput {
	return o
}

// Kubeconfig returned from AKS cluster
func (o AksKubeConfigOutput) Kubeconfig() pulumi.StringOutput {
	return o.ApplyT(func(v *AksKubeConfig) pulumi.StringOutput { return v.Kubeconfig }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*AksKubeConfigInput)(nil)).Elem(), &AksKubeConfig{})
	pulumi.RegisterOutputType(AksKubeConfigOutput{})
}
