// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package kubeconfig

import (
	"context"
	"reflect"

	"errors"
	"github.com/pierskarsenbarg/pulumi-kubeconfig/sdk/go/kubeconfig/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumix"
)

type EksKubeConfig struct {
	pulumi.CustomResourceState

	// Base64 encoded certificate data required to communicate with your cluster.
	CertificateData pulumix.Output[string] `pulumi:"certificateData"`
	// Endpoint for your Kubernetes API server.
	ClusterEndpoint pulumix.Output[string] `pulumi:"clusterEndpoint"`
	// Name of the EKS cluster you want to generate the kubeconfig for
	ClusterName pulumix.Output[string] `pulumi:"clusterName"`
	// Generated Kubeconfig for working with your EKS cluster
	Kubeconfig pulumix.Output[string] `pulumi:"kubeconfig"`
	// AWS Profile name that you want the kubeconfig to use. Optional
	ProfileName pulumix.Output[*string] `pulumi:"profileName"`
	Region      pulumix.Output[*string] `pulumi:"region"`
	// Role arn that you want the kubeconfig to use. Optional
	RoleArn pulumix.Output[*string] `pulumi:"roleArn"`
}

// NewEksKubeConfig registers a new resource with the given unique name, arguments, and options.
func NewEksKubeConfig(ctx *pulumi.Context,
	name string, args *EksKubeConfigArgs, opts ...pulumi.ResourceOption) (*EksKubeConfig, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.ClusterEndpoint == nil {
		return nil, errors.New("invalid value for required argument 'ClusterEndpoint'")
	}
	if args.ClusterName == nil {
		return nil, errors.New("invalid value for required argument 'ClusterName'")
	}
	secrets := pulumi.AdditionalSecretOutputs([]string{
		"kubeconfig",
	})
	opts = append(opts, secrets)
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource EksKubeConfig
	err := ctx.RegisterResource("kubeconfig:index:EksKubeConfig", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetEksKubeConfig gets an existing EksKubeConfig resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetEksKubeConfig(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *EksKubeConfigState, opts ...pulumi.ResourceOption) (*EksKubeConfig, error) {
	var resource EksKubeConfig
	err := ctx.ReadResource("kubeconfig:index:EksKubeConfig", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering EksKubeConfig resources.
type eksKubeConfigState struct {
}

type EksKubeConfigState struct {
}

func (EksKubeConfigState) ElementType() reflect.Type {
	return reflect.TypeOf((*eksKubeConfigState)(nil)).Elem()
}

type eksKubeConfigArgs struct {
	// Base64 encoded certificate data required to communicate with your cluster.
	CertificateData *string `pulumi:"certificateData"`
	// Endpoint for your Kubernetes API server.
	ClusterEndpoint string `pulumi:"clusterEndpoint"`
	// Name of the EKS cluster you want to generate the kubeconfig for
	ClusterName string `pulumi:"clusterName"`
	// AWS Profile name that you want the kubeconfig to use
	ProfileName *string `pulumi:"profileName"`
	// Region that the EKS cluster is in. Optional
	Region *string `pulumi:"region"`
	// Role arn that you want the kubeconfig to use. Optional
	RoleArn *string `pulumi:"roleArn"`
}

// The set of arguments for constructing a EksKubeConfig resource.
type EksKubeConfigArgs struct {
	// Base64 encoded certificate data required to communicate with your cluster.
	CertificateData pulumix.Input[*string]
	// Endpoint for your Kubernetes API server.
	ClusterEndpoint pulumix.Input[string]
	// Name of the EKS cluster you want to generate the kubeconfig for
	ClusterName pulumix.Input[string]
	// AWS Profile name that you want the kubeconfig to use
	ProfileName pulumix.Input[*string]
	// Region that the EKS cluster is in. Optional
	Region pulumix.Input[*string]
	// Role arn that you want the kubeconfig to use. Optional
	RoleArn pulumix.Input[*string]
}

func (EksKubeConfigArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*eksKubeConfigArgs)(nil)).Elem()
}

type EksKubeConfigOutput struct{ *pulumi.OutputState }

func (EksKubeConfigOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*EksKubeConfig)(nil)).Elem()
}

func (o EksKubeConfigOutput) ToEksKubeConfigOutput() EksKubeConfigOutput {
	return o
}

func (o EksKubeConfigOutput) ToEksKubeConfigOutputWithContext(ctx context.Context) EksKubeConfigOutput {
	return o
}

func (o EksKubeConfigOutput) ToOutput(ctx context.Context) pulumix.Output[EksKubeConfig] {
	return pulumix.Output[EksKubeConfig]{
		OutputState: o.OutputState,
	}
}

// Base64 encoded certificate data required to communicate with your cluster.
func (o EksKubeConfigOutput) CertificateData() pulumix.Output[string] {
	value := pulumix.Apply[EksKubeConfig](o, func(v EksKubeConfig) pulumix.Output[string] { return v.CertificateData })
	return pulumix.Flatten[string, pulumix.Output[string]](value)
}

// Endpoint for your Kubernetes API server.
func (o EksKubeConfigOutput) ClusterEndpoint() pulumix.Output[string] {
	value := pulumix.Apply[EksKubeConfig](o, func(v EksKubeConfig) pulumix.Output[string] { return v.ClusterEndpoint })
	return pulumix.Flatten[string, pulumix.Output[string]](value)
}

// Name of the EKS cluster you want to generate the kubeconfig for
func (o EksKubeConfigOutput) ClusterName() pulumix.Output[string] {
	value := pulumix.Apply[EksKubeConfig](o, func(v EksKubeConfig) pulumix.Output[string] { return v.ClusterName })
	return pulumix.Flatten[string, pulumix.Output[string]](value)
}

// Generated Kubeconfig for working with your EKS cluster
func (o EksKubeConfigOutput) Kubeconfig() pulumix.Output[string] {
	value := pulumix.Apply[EksKubeConfig](o, func(v EksKubeConfig) pulumix.Output[string] { return v.Kubeconfig })
	return pulumix.Flatten[string, pulumix.Output[string]](value)
}

// AWS Profile name that you want the kubeconfig to use. Optional
func (o EksKubeConfigOutput) ProfileName() pulumix.Output[*string] {
	value := pulumix.Apply[EksKubeConfig](o, func(v EksKubeConfig) pulumix.Output[*string] { return v.ProfileName })
	return pulumix.Flatten[*string, pulumix.Output[*string]](value)
}

func (o EksKubeConfigOutput) Region() pulumix.Output[*string] {
	value := pulumix.Apply[EksKubeConfig](o, func(v EksKubeConfig) pulumix.Output[*string] { return v.Region })
	return pulumix.Flatten[*string, pulumix.Output[*string]](value)
}

// Role arn that you want the kubeconfig to use. Optional
func (o EksKubeConfigOutput) RoleArn() pulumix.Output[*string] {
	value := pulumix.Apply[EksKubeConfig](o, func(v EksKubeConfig) pulumix.Output[*string] { return v.RoleArn })
	return pulumix.Flatten[*string, pulumix.Output[*string]](value)
}

func init() {
	pulumi.RegisterOutputType(EksKubeConfigOutput{})
}
