// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package kubeconfig

import (
	"context"
	"reflect"

	"errors"
	"github.com/pierskarsenbarg/pulumi-kubeconfig/sdk/go/kubeconfig/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumix"
)

type GkeKubeConfig struct {
	pulumi.CustomResourceState

	CertificateData pulumix.Output[*string] `pulumi:"certificateData"`
	ClusterEndpoint pulumix.Output[string]  `pulumi:"clusterEndpoint"`
	ClusterName     pulumix.Output[string]  `pulumi:"clusterName"`
	// Generated Kubeconfig for working with your GKE cluster
	Kubeconfig pulumix.Output[string] `pulumi:"kubeconfig"`
}

// NewGkeKubeConfig registers a new resource with the given unique name, arguments, and options.
func NewGkeKubeConfig(ctx *pulumi.Context,
	name string, args *GkeKubeConfigArgs, opts ...pulumi.ResourceOption) (*GkeKubeConfig, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.CertificateData == nil {
		return nil, errors.New("invalid value for required argument 'CertificateData'")
	}
	if args.ClusterEndpoint == nil {
		return nil, errors.New("invalid value for required argument 'ClusterEndpoint'")
	}
	if args.ClusterName == nil {
		return nil, errors.New("invalid value for required argument 'ClusterName'")
	}
	if args.Project == nil {
		return nil, errors.New("invalid value for required argument 'Project'")
	}
	if args.Zone == nil {
		return nil, errors.New("invalid value for required argument 'Zone'")
	}
	secrets := pulumi.AdditionalSecretOutputs([]string{
		"kubeconfig",
	})
	opts = append(opts, secrets)
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource GkeKubeConfig
	err := ctx.RegisterResource("kubeconfig:index:GkeKubeConfig", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetGkeKubeConfig gets an existing GkeKubeConfig resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetGkeKubeConfig(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *GkeKubeConfigState, opts ...pulumi.ResourceOption) (*GkeKubeConfig, error) {
	var resource GkeKubeConfig
	err := ctx.ReadResource("kubeconfig:index:GkeKubeConfig", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering GkeKubeConfig resources.
type gkeKubeConfigState struct {
}

type GkeKubeConfigState struct {
}

func (GkeKubeConfigState) ElementType() reflect.Type {
	return reflect.TypeOf((*gkeKubeConfigState)(nil)).Elem()
}

type gkeKubeConfigArgs struct {
	// Base64 encoded certificate data required to communicate with your cluster.
	CertificateData string `pulumi:"certificateData"`
	// Endpoint for your Kubernetes API server.
	ClusterEndpoint string `pulumi:"clusterEndpoint"`
	// Name of the GKE cluster you want to generate the kubeconfig for
	ClusterName string `pulumi:"clusterName"`
	Project     string `pulumi:"project"`
	Zone        string `pulumi:"zone"`
}

// The set of arguments for constructing a GkeKubeConfig resource.
type GkeKubeConfigArgs struct {
	// Base64 encoded certificate data required to communicate with your cluster.
	CertificateData pulumix.Input[string]
	// Endpoint for your Kubernetes API server.
	ClusterEndpoint pulumix.Input[string]
	// Name of the GKE cluster you want to generate the kubeconfig for
	ClusterName pulumix.Input[string]
	Project     pulumix.Input[string]
	Zone        pulumix.Input[string]
}

func (GkeKubeConfigArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*gkeKubeConfigArgs)(nil)).Elem()
}

type GkeKubeConfigOutput struct{ *pulumi.OutputState }

func (GkeKubeConfigOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GkeKubeConfig)(nil)).Elem()
}

func (o GkeKubeConfigOutput) ToGkeKubeConfigOutput() GkeKubeConfigOutput {
	return o
}

func (o GkeKubeConfigOutput) ToGkeKubeConfigOutputWithContext(ctx context.Context) GkeKubeConfigOutput {
	return o
}

func (o GkeKubeConfigOutput) ToOutput(ctx context.Context) pulumix.Output[GkeKubeConfig] {
	return pulumix.Output[GkeKubeConfig]{
		OutputState: o.OutputState,
	}
}

func (o GkeKubeConfigOutput) CertificateData() pulumix.Output[*string] {
	value := pulumix.Apply[GkeKubeConfig](o, func(v GkeKubeConfig) pulumix.Output[*string] { return v.CertificateData })
	return pulumix.Flatten[*string, pulumix.Output[*string]](value)
}

func (o GkeKubeConfigOutput) ClusterEndpoint() pulumix.Output[string] {
	value := pulumix.Apply[GkeKubeConfig](o, func(v GkeKubeConfig) pulumix.Output[string] { return v.ClusterEndpoint })
	return pulumix.Flatten[string, pulumix.Output[string]](value)
}

func (o GkeKubeConfigOutput) ClusterName() pulumix.Output[string] {
	value := pulumix.Apply[GkeKubeConfig](o, func(v GkeKubeConfig) pulumix.Output[string] { return v.ClusterName })
	return pulumix.Flatten[string, pulumix.Output[string]](value)
}

// Generated Kubeconfig for working with your GKE cluster
func (o GkeKubeConfigOutput) Kubeconfig() pulumix.Output[string] {
	value := pulumix.Apply[GkeKubeConfig](o, func(v GkeKubeConfig) pulumix.Output[string] { return v.Kubeconfig })
	return pulumix.Flatten[string, pulumix.Output[string]](value)
}

func init() {
	pulumi.RegisterOutputType(GkeKubeConfigOutput{})
}
