// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace PiersKarsenbarg.Pulumi.Kubeconfig
{
    [KubeconfigResourceType("kubeconfig:index:GkeKubeConfig")]
    public partial class GkeKubeConfig : global::Pulumi.CustomResource
    {
        [Output("certificateData")]
        public Output<string?> CertificateData { get; private set; } = null!;

        [Output("clusterEndpoint")]
        public Output<string> ClusterEndpoint { get; private set; } = null!;

        [Output("clusterName")]
        public Output<string> ClusterName { get; private set; } = null!;

        /// <summary>
        /// Generated Kubeconfig for working with your GKE cluster
        /// </summary>
        [Output("kubeconfig")]
        public Output<string> Kubeconfig { get; private set; } = null!;


        /// <summary>
        /// Create a GkeKubeConfig resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public GkeKubeConfig(string name, GkeKubeConfigArgs args, CustomResourceOptions? options = null)
            : base("kubeconfig:index:GkeKubeConfig", name, args ?? new GkeKubeConfigArgs(), MakeResourceOptions(options, ""))
        {
        }

        private GkeKubeConfig(string name, Input<string> id, CustomResourceOptions? options = null)
            : base("kubeconfig:index:GkeKubeConfig", name, null, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/pierskarsenbarg/pulumi-kubeconfig",
                AdditionalSecretOutputs =
                {
                    "kubeconfig",
                },
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing GkeKubeConfig resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static GkeKubeConfig Get(string name, Input<string> id, CustomResourceOptions? options = null)
        {
            return new GkeKubeConfig(name, id, options);
        }
    }

    public sealed class GkeKubeConfigArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Base64 encoded certificate data required to communicate with your cluster.
        /// </summary>
        [Input("certificateData", required: true)]
        public Input<string> CertificateData { get; set; } = null!;

        /// <summary>
        /// Endpoint for your Kubernetes API server.
        /// </summary>
        [Input("clusterEndpoint", required: true)]
        public Input<string> ClusterEndpoint { get; set; } = null!;

        /// <summary>
        /// Name of the GKE cluster you want to generate the kubeconfig for
        /// </summary>
        [Input("clusterName", required: true)]
        public Input<string> ClusterName { get; set; } = null!;

        [Input("project", required: true)]
        public Input<string> Project { get; set; } = null!;

        [Input("zone", required: true)]
        public Input<string> Zone { get; set; } = null!;

        public GkeKubeConfigArgs()
        {
        }
        public static new GkeKubeConfigArgs Empty => new GkeKubeConfigArgs();
    }
}
