name: pr
on:
  pull_request:
    types:
    - opened
    - reopened
    - edited
    - synchronize
jobs:
  build_all:
    name: Build all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Set Provider Version
        uses: pulumi/provider-version-action@v1
        with:
          set-env: PROVIDER_VERSION
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.21.x"
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - name: Setup DotNet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "6.0.302"
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install Pulumi CLI
        uses: pulumi/actions@v6
        with:
          pulumi-version: "3.136.0"
      - name: Check Pulumi CLI version
        run: pulumi version
      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install pulumictl
        uses: jaxxstorm/action-install-gh-release@v1.13.0
        with:
          repo: pulumi/pulumictl
      - name: generate sdks
        run: task generate_sdks
      