name: pr
on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize

env:
  PROVIDER_NAME: pulumi-resource-kubeconfig

jobs:
  build_provider:
    name: Build Provider binary
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v6
      - name: Get short commit sha
        id: short_commit_sha
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: Set Provider Version
        uses: pulumi/provider-version-action@v1
        with:
          set-env: PROVIDER_VERSION
      - name: Install Go
        uses: actions/setup-go@v6
        with:
          go-version: "1.26.x"
      - name: Install Pulumi CLI
        uses: pulumi/actions@v6
        with:
          pulumi-version: latest
      - name: Check Pulumi CLI version
        run: pulumi version
      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install pulumictl
        uses: jaxxstorm/action-install-gh-release@v3.0.0
        with:
          repo: pulumi/pulumictl
      - name: Install GoReleaser
        uses: goreleaser/goreleaser-action@v7
        with:
          install-only: true
      - name: Build provider
        run: task ci_pr_build_provider
      - name: Upload artifacts
        uses: actions/upload-artifact@v7
        with:
          name: ${{ env.PROVIDER_NAME }}.tar.gz
          path: ${{ github.workspace }}/dist/pulumi-resource-kubeconfig-${{ steps.short_commit_sha.outputs.sha_short}}-linux-arm64.tar.gz

  # build_all:
  #   name: Build all
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout Repo
  #       uses: actions/checkout@v6
  #     - name: Set Provider Version
  #       uses: pulumi/provider-version-action@v1
  #       with:
  #         set-env: PROVIDER_VERSION
  #     - name: Install Go
  #       uses: actions/setup-go@v6
  #       with:
  #         go-version: "1.26.x"
  #     - name: Setup Node
  #       uses: actions/setup-node@v6
  #       with:
  #         node-version: "22.x"
  #     - name: Setup DotNet
  #       uses: actions/setup-dotnet@v5
  #       with:
  #         dotnet-version: "10.0.201"
  #     - name: Setup Python
  #       uses: actions/setup-python@v6
  #       with:
  #         python-version: "3.11"
  #     - name: Install Pulumi CLI
  #       uses: pulumi/actions@v6
  #       with:
  #         pulumi-version: latest
  #     - name: Check Pulumi CLI version
  #       run: pulumi version
  #     - name: Install Task
  #       uses: arduino/setup-task@v2
  #       with:
  #         version: 3.x
  #         repo-token: ${{ secrets.GITHUB_TOKEN }}
  #     - name: Install pulumictl
  #       uses: jaxxstorm/action-install-gh-release@v3.0.0
  #       with:
  #         repo: pulumi/pulumictl
  #     - name: generate sdks
  #       run: task generate_sdks
  #   strategy: 
  #     fail-fast: true
  #     matrix:
  #       language:
  #         - nodejs
  #         - python
  #         - go
  #         - dotnet
