name: release
"on":
  push:
    tags:
      - v*.*.*
      - "!v*.*.*-**"

permissions:
  id-token: write
  contents: write

env:
  PROVIDER: kubeconfig
  GO_VERSION: "1.26.x"
  NODEJS_VERSION: "24.x"
  DOTNET_VERSION: "10.0.201"
  PYTHON_VERSION: "3.12"
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  PROVIDER_NAME: pulumi-resource-kubeconfig

jobs:
  publish_provider:
    runs-on: ubuntu-latest
    name: publish_provider
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v6
      - name: Unshallow clone for tags
        run: git fetch --prune --unshallow --tags
      - name: Install Go
        uses: actions/setup-go@v6
        with:
          go-version: ${{env.GO_VERSION}}
          cache-dependency-path: "**/*.sum"
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v7
        with:
          args: release --clean --timeout 60m0s
          version: "~> v2"
      - name: Compress linux amd64 binary
        run: tar -zcf ${{ github.workspace }}/${{env.PROVIDER_NAME}}.tar.gz -C ${{ github.workspace }}/dist/pulumi-${{env.PROVIDER}}_linux_amd64_v1 ${{env.PROVIDER_NAME}}
      - name: Upload artifacts
        uses: actions/upload-artifact@v7
        with:
          name: ${{env.PROVIDER_NAME}}.tar.gz
          path: ${{ github.workspace }}/${{env.PROVIDER_NAME}}.tar.gz
  
  build_sdks:
    name: Build provider SDKs
    runs-on: ubuntu-latest
    needs: publish_provider
    strategy:
        fail-fast: true
        matrix:
          language:
            - nodejs
            - python
            - dotnet
            - go
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v6
      - name: Set Provider Version
        uses: pulumi/provider-version-action@v1
        with:
          set-env: PROVIDER_VERSION
      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install Pulumi CLI
        uses: pulumi/actions@v6
        with:
          pulumi-version: latest
      - name: Check Pulumi CLI version
        run: pulumi version
      - name: Install pulumictl
        uses: jaxxstorm/action-install-gh-release@v3.0.0
        with:
          repo: pulumi/pulumictl
      - if: matrix.language == 'nodejs'
        name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: ${{ env.NODEJS_VERSION }}
      - if: matrix.language == 'dotnet'
        name: Setup DotNet
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - if: matrix.language == 'python'
        name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - if: matrix.language == 'go'
        name: Install Go
        uses: actions/setup-go@v6
        with:
          go-version: ${{env.GO_VERSION}}
      - name: Download provider binary
        uses: actions/download-artifact@v8
        with:
          name: ${{ env.PROVIDER_NAME }}.tar.gz
          path: ${{ github.workspace }}/bin
      - name: Untar provider binary
        run: |-
          tar -zxf ${{ github.workspace }}/bin/${{ env.PROVIDER_NAME }}.tar.gz -C ${{ github.workspace }}/bin
          chmod +x ${{ github.workspace }}/bin/${{ env.PROVIDER_NAME }}
      - name: Build ${{ matrix.language }} SDK
        run: task generate_${{ matrix.language }}_sdk
      - name: Compress SDK folder
        run: tar -zcf sdk/${{ matrix.language }}.tar.gz -C sdk/${{ matrix.language }} .
      - name: Upload artifacts
        uses: actions/upload-artifact@v7
        with:
          name: ${{ matrix.language  }}.tar.gz
          path: ${{ github.workspace}}/sdk/${{ matrix.language }}.tar.gz

  
  publish_sdks:
    runs-on: ubuntu-latest
    needs: build_sdks
    strategy:
      fail-fast: true
      matrix:
        language:
          - nodejs
          - python
          - dotnet
    steps:
      - if: matrix.language == 'nodejs'
        name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: ${{env.NODEJS_VERSION}}
          registry-url: https://registry.npmjs.org
      - if: matrix.language == 'dotnet'
        name: Setup DotNet
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: ${{env.DOTNET_VERSION}}
      - if: matrix.language == 'python'
        name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{env.PYTHON_VERSION}}
      - name: Download ${{matrix.language}} SDK
        uses: actions/download-artifact@v8
        with:
          name: ${{matrix.language}}.tar.gz
          path: ${{ github.workspace}}/sdk/
      - name: Create ${{matrix.language}} directory
        run: mkdir -p ${{github.workspace}}/sdk/${{matrix.language}}
      - name: Uncompress ${{matrix.language}} SDK
        run: tar -zxf ${{github.workspace}}/sdk/${{matrix.language}}.tar.gz -C ${{github.workspace}}/sdk/${{matrix.language}}
      - if: matrix.language == 'python'
        name: Publish PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: ${{github.workspace}}/sdk/python/bin/dist
      - if: matrix.language == 'nodejs'
        name: Publish NPM package
        run: npm publish --access public
        working-directory: ${{github.workspace}}/sdk/nodejs/bin
      - if: matrix.language == 'dotnet'
        name: Publish Nuget package
        env:
          NUGET_PUBLISH_KEY: ${{ secrets.NUGET_PUBLISH_KEY }}
        run: find "${{github.workspace}}/sdk/dotnet/bin/Release/" -name 'PiersKarsenbarg.*.nupkg' -exec dotnet nuget push -k "${NUGET_PUBLISH_KEY}" -s https://api.nuget.org/v3/index.json {} ';'
  
  publish_go_sdk:
    runs-on: ubuntu-latest
    name: publish-go-sdk
    needs: publish_sdks
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v6
      - id: version
        name: Set Provider Version
        uses: pulumi/provider-version-action@v1
        with:
          set-env: PROVIDER_VERSION
      - name: Download go SDK
        uses: actions/download-artifact@v8
        with:
          name: go.tar.gz
          path: ${{ github.workspace}}/sdk/
      - name: Uncompress go SDK
        run: tar -zxf ${{github.workspace}}/sdk/go.tar.gz -C
          ${{github.workspace}}/sdk/go
      - name: Publish Go SDK
        uses: pulumi/publish-go-sdk-action@v1
        with:
          repository: ${{ github.repository }}
          base-ref: ${{ github.sha }}
          source: sdk/go/kubeconfig
          path: sdk/go/kubeconfig
          version: ${{ steps.version.outputs.version }}
          additive: false
          files: "**"
